# Generated by Django 4.1.5 on 2023-02-10 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
    ]
